### ISSUE TITLE
freeList为啥每个节点信息都一样

### ISSUE THREAD

**Issue by GitHdu** [h7ml/okjiasu_action#20]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by GitHdu** [comment]
https://github.com/h7ml/okjiasu_action/blob/a76a1ed053759243ffaf20e5571d2bae65fa8d9e/package/okjiasu/free.js#L74

这里有问题，取到的framUrl都是最后一个

**Comment by h7ml** [comment]
> https://github.com/h7ml/okjiasu_action/blob/a76a1ed053759243ffaf20e5571d2bae65fa8d9e/package/okjiasu/free.js#L74
> 
> 这里有问题，取到的framUrl都是最后一个
> 
> ```js
> // 改成继发点击
> const getFreescribeUrl = async (page) => {
>   let subscribeUrl = [];
>   const n = await page.$$(".media", (element) => element);
>   console.log(`${nowTime()} : 获取到 ${n.length} 个免费节点`);
>   // 有效节点
>   const validNode = await page.$$(".node-is-online", (element) => element);
>   // 点击每个节点
> 
>   const actions = validNode.map(async (item, index) => {
>       await page.waitForTimeout(1000);
>       await item.executionContext().evaluate((item) => item.click({ delay: 50 }), item)
>       const textInfo = await item
>         .executionContext()
>         .evaluate((item) => item.textContent, item);
>       console.log(`${nowTime('YYYY-MM-DDTHH:mm:ssZ[Z]')} : 点击节点 ${textInfo}`);
>       // 打开iframe id 为 infoifram 的src地址
>       await page.waitForTimeout(1000);
>       await page.waitForSelector("#infoifram");
>       const iframeUrl = await getElementAttribute(page, "#infoifram", "src");
>       const [
>         order, text, url, detail
>         //  online, ratio, load, rate
>       ] = [
>           index + 1,// 序号,
>           textInfo.replaceAll(" ", "").replaceAll('|', ''), // 节点名称
>           'https://zhuri.cc/user/' + iframeUrl.replaceAll('./', ''),
>           {
>             "ip": "",
>             "port": "",
>             "alterID": "",
>             "UUid": "",
>             "protocol": "",
>             "vmess": "",
>             "qrcode": ""
>           },
>           '',// 在线人数
>           '', // 速度比例
>           '',// 负载
>           '', // 速率
>         ];
>       console.log(`${nowTime('YYYY-MM-DDTHH:mm:ssZ[Z]')} : 获取到第${order}的节点${text}订阅链接 ${url}`);
>       subscribeUrl.push({
>         order, text, url, detail
>       });
>       await page.click("span[aria-hidden='true']");
>       await page.waitForTimeout(1000);
>     })
>     for (const action of actions) {
>       await action()
>     }
> 
>   console.log(`${nowTime()} : 节点信息采集完毕`);
>   return subscribeUrl;
> };
> ```

我排查下。

**Comment by h7ml** [comment]
![image](https://user-images.githubusercontent.com/55233292/233849568-63c06e61-a479-44d5-a908-3377320fb151.png)
确实存在这个问题。

**Comment by h7ml** [comment]
https://github.com/h7ml/okjiasu_action/actions/runs/4788275836/jobs/8514650825  

![image](https://user-images.githubusercontent.com/55233292/234048723-6f48d880-3b59-4038-af80-cc375f45f4ab.png)

修复了。。
